#!/bin/bash

url="https://files.minecraftforge.net/net/minecraftforge/forge/"
echo "Downloading source code from $url..."
targetUrl=$(curl -s "$url" | \
              grep -o 'https://adfoc.us/serve/sitelinks/?id=271228&url=[^"]*' | \
              head -n 1 | \
              curl -s "$url" | \
              grep -o 'https://adfoc.us/serve/sitelinks/?id=271228&url=[^"]*' | \
              head -n 1 | \
              sed 's|https://adfoc.us/serve/sitelinks/?id=271228&url=||')
curl -o "forge-server.jar" "$targetUrl"
java -Xmx4G -jar forge-server.jar --installServer
rm forge-server.jar forge-server.jar.log
./run.sh --initSettings
