#!/bin/bash

curl -OSs https://raw.githubusercontent.com/ayu2805/forge-server/main/linux-forge-server
chmod +x linux-forge-server
url="https://files.minecraftforge.net/net/minecraftforge/forge/"
echo "Downloading source code from $url..."
targetUrl=$(curl -s "$url" | \
            grep -o 'https://adfoc.us/serve/sitelinks/?id=271228&url=[^"]*' | \
            head -n 1 | \
            sed 's|https://adfoc.us/serve/sitelinks/?id=271228&url=||')
curl -o "forge.jar" "$targetUrl"
//java -jar forge.jar --installClient ~/.minecraft
java -jar forge.jar --installServer
rm forge.jar forge-server.jar.log
./run.sh --initSettings
